/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./src/components/shared/EmptyState.vue')['default']
    ErrorAlert: typeof import('./src/components/shared/ErrorAlert.vue')['default']
    ErrorDisplay: typeof import('./src/components/ErrorDisplay.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    LoadingSpinner: typeof import('./src/components/shared/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateWrapper: typeof import('./src/components/shared/StateWrapper.vue')['default']
    ThemeToggle: typeof import('./src/components/shared/ThemeToggle.vue')['default']
    ToastProvider: typeof import('./src/components/ui/ToastProvider.vue')['default']
  }
}
